export type Roster = RosterYear[];

export interface RosterYear {
  year: string;
  chairs?: RosterMember[];
  teams?: RosterTeam[];
  error?: string;
}

export interface RosterTeam {
  name: string;
  executive: RosterMember[];
  general: RosterMember[];
}

export type RosterMember = string | { name: string; url: string };

export const roster: Roster = sorted([
  {
    year: '2025',
    chairs: ['Defne Deda', 'Alex Kahn'],
    teams: [
      {
        name: 'Booking',
        executive: ['Nathan Dent'],
        general: [
          'Payton Marino',
          'Timia Quincy McCoade',
          'Rachana Aluri',
          'Sebastian Huerta',
          'Avalon Bookstaver',
          'Mariam Fofana',
          'Ani Rao',
        ],
      },
      {
        name: 'Community',
        executive: ['Eleanor Dempsey', 'Emma Kogan'],
        general: [
          'Anya Bardach',
          'Danielle Nevett',
          'Payton DiSario',
          'Risha Hussain',
          'Rukevwe Alade',
          'Sakina Husein',
          'Serena Bentum-Siripi',
          'Tyler Kang',
          'Ozge Bahar Unver',
        ],
      },
      {
        name: 'Corporate',
        executive: ['Ali Lee', 'Tyler Keim'],
        general: [
          'Olivia (Liv) Clark',
          'Adam Valiji',
          'Grace Shao',
          'Gio Cacciato',
          'Jonathan Lee',
          'Maddie Wang',
          'Morrie Schonfeld',
          'Anthony Scarmozzino',
        ],
      },
      {
        name: 'Finance',
        executive: ['Aimee Chooi', 'Zander Sy'],
        general: [
          'Quinn Shumway',
          'Nico Antezano',
          'Charlene Chang Kurniawan',
          'Luke Fosdick',
          'Roberto Borsetti',
          'Sarah Kim',
        ],
      },
      {
        name: 'Production',
        executive: ['Keyanna Adams', 'Ethan Sterling'],
        general: [
          'Connor Capoot',
          'Irem Ozsavasci',
          'Asha Buerk',
          'Emma Brown',
          'Jack Ryzenman',
          'Grace Herzog',
          'Keya Umesh',
          'Rishi Shah',
          'Yaewon Woo',
        ],
      },
      {
        name: 'Programming',
        executive: ['Cat Johnston'],
        general: [
          'Joel Reyes',
          'Levy Deckard',
          'Luke Incardona',
          'Autumn Grieb',
          'Caryl Shepard',
          'Ellen Kim',
          'Paige Usry',
          'Anais Duewel',
        ],
      },
      {
        name: 'Promotions',
        executive: ['Seeley McGills', 'Felipe Reis Maccari'],
        general: [
          'Annabel Goldman',
          'Lauren Lin',
          'Anoushka Dasgupta',
          'Glorietta Arthoro',
          'Lee Ekong',
          'Alicia Gu',
          'Jackie Li',
          'Joss Broward',
          'Shreya Rallabandi',
          'Katareena Roska',
          'Michelle Nartey',
        ],
      },
      {
        name: 'Technology',
        executive: ['Ethan Pineda'],
        general: [
          'Sofia Melendez',
          'Cate Rose',
          'David Fu',
          'Eduardo Ramos',
          'Vivian Chen',
          'Jenna Kazim',
          'Leo Garcia',
        ],
      },
      {
        name: 'Operations',
        executive: ['Natalie Gurganus', 'Chloe Coenraets'],
        general: [
          'Emiliano Ghislieri',
          'Gabby Garcia',
          'Sam Albright',
          'Adam Durr',
          'Jing Xi Yap',
          'Marina Shirky',
          'Shae Lake',
          'Brendan Howard',
          'Henry Park',
          'Lauren Ryoo',
          'Lexi Sullivan',
        ],
      },
    ],
  },
  {
    year: '2024',
    chairs: ['Darya Daneshmand', 'Alex Kahn'],
    teams: [
      {
        name: 'Booking',
        executive: ['Armaan Ajani'],
        general: [
          'Payton Marino',
          'Nathan Dent',
          'Timia Quincy McCoade',
          'Skylar Deeter',
          'Jack Ding',
          'Elena Hubert',
          'Maya Shadid',
          'Sebastian Huerta',
        ],
      },
      {
        name: 'Community',
        executive: ['Anabel Marre', 'Emma Kogan'],
        general: [
          'Payton DiSario',
          'Anya Bardach',
          'Danielle Nevett',
          'Risha Hussain',
          'Eleanor Dempsey',
          'Sakina Husein',
          'Rukevwe Alade',
        ],
      },
      {
        name: 'Corporate',
        executive: ['Ali Lee'],
        general: [
          'Quinn Shumway',
          'Olivia Clark',
          'Adam Valiji',
          'Matt Lee',
          'Stephanie Shields',
          'Jason Huang',
          'Grace Shao',
          'Jonathan Lee',
        ],
      },
      {
        name: 'Finance',
        executive: ['Priya Dave', 'Aimee Chooi'],
        general: ['Donny Tou', 'Zander Sy', 'Ashley Zhang', 'Rudy Danda'],
      },
      {
        name: 'Production',
        executive: ['Ada Zhong', 'Irem Ozsavasci'],
        general: [
          'Jack Burkhardt',
          'Thomas Silberberg',
          'Connor Capoot',
          'Keyanna Adams',
          'Caitlin Riley',
          'Marina Shirky',
          'Ethan Sterling ',
          'Emma Brown',
          'Asha Buerk',
        ],
      },
      {
        name: 'Programming',
        executive: ['Cat Johnston'],
        general: [
          'Luke Incardona',
          'Caryl Shepard',
          'Joel Angelito',
          'Eduardo Ramos',
          'Autumn Grieb',
        ],
      },
      {
        name: 'Promotions',
        executive: ['Defne Deda', 'Tyler Keim'],
        general: [
          'Catherine Duncan',
          'Annabel Goldman',
          'Seeley McGillis',
          'Felipe Reis Maccari',
          'Victoria Tran',
          'Jessica Vallan',
          'Rachana Aluri',
          'Glorietta Arthoro',
          'Lee Ekong',
          'Joss Broward',
          'Anoushka Dasgupta',
          'Lauren Lin',
        ],
      },
      {
        name: 'Technology',
        executive: ['Dilan Nair'],
        general: [
          'Cheryl Lin',
          'Mahmood Sadeghi',
          'Andy Vu',
          'Vivian Chen',
          'David Fu',
          'Cate Rose',
        ],
      },
      {
        name: 'Operations',
        executive: ['Caroline Labow', 'Lahari Ramini'],
        general: [
          'Sam Albright',
          'Natalie Gurganus',
          'Chloe Coenraets',
          'Noah Seth',
          'Emiliano Ghislieri',
          'Gabby Garcia',
          'Jing Xi Yap',
          'Shae Lake',
          'Adam Durr',
        ],
      },
      {
        name: 'General Board',
        executive: ['Darya Daneshmand', 'Alex Kahn'],
        general: [
          'Gio Cacciato',
          'Rishi Shah',
          'Grace Herzog',
          'Alicia Gu',
          'Isabella Pongracz',
          'Yaewon Woo',
          'Mariam Fofana',
          'Morrie Schonfield',
          'Brendan Howard',
          'Jack Ryzenman',
          'Anais Duewel',
          'Keya Umesh',
          'Avalon Bookstaver',
          'Luke Fosdick',
        ],
      },
    ],
  },
  {
    year: '2023',
    chairs: ['Nicole Tank', 'Amya Scott'],
    teams: [
      {
        name: 'Booking',
        executive: ['Jack Ding'],
        general: [
          'Samad Acklin',
          'Levi Saltzman',
          'Nathan Dent',
          'Maggie Lezcano',
          'Skylar Deeter',
          'Sami Contractor',
          'Armaan Ajani',
          'Elena Hubert',
          'Maya Shadid',
        ],
      },
      {
        name: 'Community',
        executive: ['Sabrina Scheinberg', 'Anabel Marre'],
        general: [
          'Payton DiSario',
          'Emma Kogan',
          'Anya Bardach',
          'Danielle Nevett',
          'Jagan Nallani',
          'Risha Hussain',
        ],
      },
      {
        name: 'Corporate',
        executive: ['Stuart Sumner'],
        general: [
          'Annabel Goldman',
          'Graham Umbanhowar',
          'Quinn Shumway',
          'Olivia Clark',
          'Adam Valiji',
          'Olivia Lee',
          'Matt Lee',
          'Stephanie Shields',
          'Ali Lee',
        ],
      },
      {
        name: 'Finance',
        executive: ['Elina Rawat', 'Priya Dave'],
        general: [
          'Aimee Chooi',
          'Donny Tou',
          'Zach Blank',
          'Jasmine Tran',
          'Aerin Gelblum',
        ],
      },
      {
        name: 'Production',
        executive: ['Sierra Thoulouis', 'Caitlin Riley'],
        general: [
          'Jack Burkhardt',
          'Thomas Silberberg',
          'Irem Ozsavasci',
          'Connor Capoot',
          'Keyanna Adams',
          'Alex Kahn',
          'Liliana Castillo',
          'Ada Zhong',
        ],
      },
      {
        name: 'Programming',
        executive: ['Hannah Magrisi'],
        general: [
          'Kimberly Cruz',
          'Isabelle Chin',
          'Daisy Brockhouse',
          'Maria Charisi',
          'Kelly Alvarez',
          'Kaliyah Gowing',
          'Cat Johnston',
        ],
      },
      {
        name: 'Promotions',
        executive: ['Darya Daneshmand', 'Catherine Duncan'],
        general: [
          'Tyler Keim',
          'Catherine Zhao',
          'Seeley McGillis',
          'Haris Bukaric',
          'Felipe Reis Maccari',
          'Eddie Ko',
          "Lucas Sant'Anna",
          'Victoria Tran',
          'Jessica Vallan',
          'Defne Deda',
        ],
      },
      {
        name: 'Technology',
        executive: ['Jeff Lee'],
        general: [
          'Zach Delson',
          'Dilan Nair',
          'Cheryl Lin',
          'Mahmood Sadeghi',
          'Sungbin Yun',
          'Aly Park',
          'Emma Mansell',
        ],
      },
      {
        name: 'Operations',
        executive: ['AJ Rosenthal', 'Hannah Cheves'],
        general: [
          'Sam Albright',
          'Natalie Gurganus',
          'Lahari Ramini',
          'Noah Seth',
          'Emiliano Ghislieri',
          'Gabby Garcia',
          'Sophi Pennex',
          'Dakota DeVore',
          'Brennan Shin',
          'Caroline Labow',
        ],
      },
      {
        name: 'General Board',
        executive: ['Amya Scott', 'Nicole Tank'],
        general: [
          'Eleanor Dempsey',
          'Sakina Husein',
          'Eliana Banks',
          'Payton Marino',
          'Marina Shirky',
          'Eytan Raviv',
          'Zander Sy',
          'Ethan Sterling',
          'Chloe Coenraets',
          'Timia Quincy McCoade',
          'Emma Brown',
          'Jing Xi Yap',
          'Asha Buerk',
          'Rachana Aluri',
          'Glorietta Arthoro',
          'Rukevwe Alade',
        ],
      },
    ],
  },
  {
    year: '2022',
    chairs: ['Maryam Ikuforiji', 'Gina Waweru'],
    teams: [
      {
        name: 'Booking',
        executive: ['Ethan Shanfeld'],
        general: [
          'Arianna Staton',
          'Christian Wade',
          'Zach Fox',
          'Maggie Lezcano',
          'Skylar Deeter',
          'Jack Ding',
          'Sami Contractor',
          'Armaan Ajani',
        ],
      },
      {
        name: 'Corporate',
        executive: ['Olivia Lee'],
        general: [
          'Annie Grasse',
          'Drew Myers',
          'Owen Otkay',
          'Stuart Sumner',
          'Ray Tsao',
          'Anabel Marre',
          'Stephanie Shields',
          'Ali Lee',
        ],
      },
      {
        name: 'Diversity, Inclusion, and Wellness',
        executive: ['Samad Acklin', 'Hannah Magrisi'],
        general: [],
      },
      {
        name: 'Finance',
        executive: ['Joshua Gruen', 'Zach Blank'],
        general: [
          'Jasmine Tran',
          'Elina Rawat',
          'Aerin Gelblum',
          'Zach Delson',
        ],
      },
      {
        name: 'Production',
        executive: ['Margot Bartol', 'Amya Scott'],
        general: [
          'Eli Doroshow',
          'Ellie Coleman',
          'Ashley Fang',
          'Montserrat Vazquez-Posada',
          'Sierra Thoulouis ',
          'Liliana Castillo',
          'Ada Zhong',
          'Caitlin Riley',
        ],
      },
      {
        name: 'Programming',
        executive: ['Gavin Parisi', 'Sabrina Scheinberg'],
        general: [
          'Mari Gashaw',
          'Jerry Zhang',
          'Ronit Kitei',
          'Pablo Rodriguez',
          'Kimberly Cruz',
          'Isabelle Chin',
          'Daisy Brockhouse',
          'Graham Umbanhowar',
        ],
      },
      {
        name: 'Promotions',
        executive: ['Conor Metz', 'Nicole Tank'],
        general: [
          'Geena Vetula',
          'Alana Friedman',
          'Grace Koplin',
          'Andrea Bian',
          'Darya Daneshmand',
          "Lucas Sant'Anna",
          'Victoria Tran',
          'Catherine Duncan',
          'Jessica Vallan',
          'Defne Deda',
        ],
      },
      {
        name: 'Technology',
        executive: ['Emily Makedon'],
        general: ['Jeff Lee', 'Aly Park', 'Emma Mansell'],
      },
      {
        name: 'University Relations',
        executive: ['Elizabeth Christoph', 'AJ Rosenthal'],
        general: [
          'Daniel Rodriguez',
          'Chandler Wright',
          'Alex Chang',
          'Hannah Cheeves',
          'Sophi Pennex',
          'Dakota DeVore',
          'Sara Adurkar',
          'Brennan Shin',
          'Caroline Labow',
        ],
      },
      {
        name: 'General Board',
        executive: ['Maryam Ikuforiji', 'Gina Waweru'],
        general: [
          'Jack Burkhardt',
          'LuLu Madise',
          'Thomas Silberberg',
          'Sam Albright',
          'Annabel Goldman',
          'Irem Ozsavasci',
          'Connor Capoot',
          'Keyanna Adams',
          'Tyler Keim',
          'Sungbin Yun',
          'Nathan Dent',
          'Levi Saltzman',
          'Alex Kahn',
          'Gabby Garcia',
          'Matt Lee',
        ],
      },
    ],
  },
  {
    year: '2021',
    error: 'We do not have accurate data for this year.',
  },
  {
    year: '2020',
    error:
      'Executive member data is missing from this year, thus all members are listed as general.',
    chairs: ['Nic Khang', 'Rocco Palermo'],
    teams: [
      {
        name: 'Booking',
        executive: [],
        general: [
          'Eric Cunningham',
          'Alanna Ramquist',
          'Kelsey Adamitis',
          'Ryan Coleman',
          'Jess Viti',
          'Alex Chang',
          'Amirah Ford',
          'Akansha Raj',
          'Annie Grasse',
          'Savion Jean Pierre',
        ],
      },
      {
        name: 'Corporate',
        executive: [],
        general: [
          'Matt Reay',
          'Matthew Threadgill',
          'Drew Meyers',
          'Drew Vasquez',
          'Jamie Woodworth',
          'Renee Kim',
          'Olivia Lee',
          'Ray Tsao',
        ],
      },
      {
        name: 'Finance',
        executive: [],
        general: [
          'Jacob Lending',
          'Dale Pyoun',
          'JT Surlis',
          'Valentina Rodriguez',
          'Joshua Gruen',
          'Ava Cheevers',
          'Eric Friswold',
        ],
      },
      {
        name: 'Production',
        executive: [],
        general: [
          'Paige Hennion',
          'Zach Colton-Max',
          'Emmanuel Ogunlana',
          'June Warde',
          'Rachel Kupfer',
          'Ashley Fang',
          'Eli Doroshow',
          'Ellie Coleman',
          'Gina Waweru',
          'Margot Bartol',
        ],
      },
      {
        name: 'Programming',
        executive: [],
        general: [
          'Noelle Torres',
          'Steph Block',
          "Erin O'Loughlin",
          'Yulan Chen',
          'Becky Chen',
          'Kaitlyn Dutchin',
          'Jake Montgomery',
          'Mari Gashaw',
          'Ela Dayanikli',
          'Gavin Parisi',
          'Jerry Zhang',
          'Ronit Kitei',
        ],
      },
      {
        name: 'Promotions',
        executive: [],
        general: [
          'Eshanika Chadhury',
          'Haley Davis',
          'Alexandra Lewin',
          'Michael Del Rosario',
          'Maryam Ikuforiji',
          'Alana Friedman',
          'Andrea Bian',
          'Conor Metz',
          'Geena Vetula',
          'Grace Koplin',
          'Sarah Dagher',
        ],
      },
      {
        name: 'Technology',
        executive: [],
        general: [
          'Swapnanil Deb',
          'Abhinav Reddy',
          'Andrew Huh',
          'Parker Ryan',
          'Mohini Gupta',
          'Emily Makedon',
        ],
      },
      {
        name: 'University Relations',
        executive: [],
        general: [
          'Zack Zuzelo',
          'Juan Zuniga',
          'Ethan Larson',
          'Elise Forst',
          'Tiboo Mehta',
          'Arianna Staton',
          'Chandler Wright',
          'Elizabeth Christoph',
        ],
      },
      {
        name: 'General Board',
        executive: [],
        general: [
          'Ethan Shanfeld',
          'Montserrat Vazquez-Posada',
          'Owen Oktay',
          'AJ Rosenthal',
          'Amya Scott',
          'Arthur Lebovitz',
          'Brennan Shin',
          'Hannah Cheves',
          'Kimberly Cruz',
          'Maggie Lezcano',
          'Natalie Simbolon',
          'Nicole Tank',
          'Pablo Rodriguez',
          'Samad Acklin',
          'Sierra Thoulouis',
          'Sooim Kang',
        ],
      },
    ],
  },
  {
    year: '2019',
    error:
      'Executive member data is missing from this year, thus all members are listed as general.',
    chairs: ['Emily Davidson', 'Molly Dudas'],
    teams: [
      {
        name: 'Concerts',
        executive: [],
        general: [
          'Kiki Meiners-Rios',
          'Alanna Ramquist',
          'Jessica Viti',
          'Eric Cunningham',
          'Charles Lemoine',
          'Jon Huang',
          'Kelsey Adamitis',
          'Ryan Coleman',
        ],
      },
      {
        name: 'Programming',
        executive: [],
        general: [
          'Annabel Gordon',
          'Defne Cezayirli',
          'Jake Montgomery',
          'Mark Berger',
          'Billy Loveman',
          'Steph Block',
          'Noelle Torres',
          "Erin O'Loughlin",
          'Yulan Chen',
          'Ellie Coleman',
          'Becky Chen',
        ],
      },
      {
        name: 'Promotions',
        executive: [],
        general: [
          'Haley West',
          'Nic Khang',
          'Tilly Freedman',
          'Michael Del Rosario',
          'Zoe Juanitas',
          'Maryam Ikuforiji',
          'Haley Davis',
          'Eshanika Chadhury',
          'Alexandra Lewin',
          'Danny Fertelmeister',
          'Sarah Wong',
          'Tom Large',
          'Nancy Yao',
          'Swapnanil Deb',
          'Paul Farcasanu',
          'Emmy Khwasam-Ang',
        ],
      },
      {
        name: 'University Relations',
        executive: [],
        general: [
          'Ethan Larson',
          'Zack Zuzelo',
          'Juan Zuniga',
          'Tiboo Mehta',
          'Elise Forst',
          'Matt Reay',
          'Hannah Waxman',
        ],
      },
      {
        name: 'Production',
        executive: [],
        general: [
          'Rocco Palermo',
          'Shiv Subrahmanian',
          'Paige Hennion',
          'Rachel Kupfer',
          'Zack Colton-Max',
          'June Warde',
          'Sophia Gholdoian',
          'Carter Mohs',
          'Cameron Witz',
          'Jess Collins',
          'Kate Meyers',
        ],
      },
      {
        name: 'Corporate',
        executive: [],
        general: [
          'Chad Novek',
          'Sofia Debbiche',
          'Makenna Littlejohn',
          'Ingrid Cherry',
          'Kaitlyn Dutchin',
          'Andrew Vasquez',
          'Drew Meyers',
        ],
      },
      {
        name: 'Finance',
        executive: [],
        general: [
          'Jacob Lending',
          'Dale Pyoun',
          'Joshua Gruen',
          'Valentina Rodriguez',
          'JT Surlis',
        ],
      },
      {
        name: 'General Board',
        executive: [],
        general: [
          'Gina Waweru',
          'Alex Chang',
          'Andrea Bian',
          'Bruna Souza do Rosario',
          'Amirah Ford',
          'Alana Friedman ',
          'Ronit Kitei ',
          'Margot Bartol ',
          'Grace Koplin',
          'Emma Austin Stein',
          'Gavin Parisi',
          'Eli Doroshow ',
          'Chandler Wright',
          'Matthew Threadgill',
          'Patryk Koyt',
          'Conor Metz',
        ],
      },
    ],
  },
  {
    year: '2018',
    error: 'We do not have accurate data for this year.',
  },
  {
    year: '2017',
    chairs: ['Ben Bass', 'Joe Fowler'],
    teams: [
      {
        name: 'Production',
        executive: ['Eli Panken', 'Josh Schwartz-Dodek'],
        general: [
          'Isabel Schwartz',
          'Ben Zimmermann',
          'Amanda Charlow',
          'Blake Scott',
          'Noah Piwonka',
          'Carter Mohs',
          'Emily Davidson',
          'Shiv Subrahmanian',
          'Cam Witz',
        ],
      },
      {
        name: 'University Relations',
        executive: ['Andrew Hunter', 'Keaton Sullivan'],
        general: [
          'Ryan Wexler',
          'Sharon Fan',
          'Kody Keckler',
          'Efe Saatci',
          'Isabella Jiao',
          'Max Leef',
        ],
      },
      {
        name: 'Finance',
        executive: ['Bob Hayes'],
        general: [],
      },
      {
        name: 'Concerts',
        executive: ['Yumi Mannarelli'],
        general: ['Rovik Robert'],
      },
      {
        name: 'Wellness',
        executive: ['Rovik Robert'],
        general: [],
      },
      {
        name: 'General Board',
        executive: ['Ben Bass', 'Joe Fowler'],
        general: [
          'Alanna Ramquist',
          'Danny Fertelmeister',
          'Lizzie Weissman',
          "Erin O'Loughlin",
          'Ethan Larson',
          'John Tanasijevich',
          'Max Totsky',
          'Nicholas Khang',
          'Paige Hennion',
          'Rocco Palermo',
          'Yulan Chen',
          'Zack Zuzelo',
          'Noelle Torres',
          'Danielle Underwood',
          'Jessica Collins',
          'Jonah Philips',
          'Kate Meyers',
          'Kevin Liang',
          'Kiki Meiners-Rios',
          'Mark Berger',
        ],
      },
    ],
  },
  {
    year: '2016',
    error: 'We do not have accurate data for this year.',
  },
  {
    year: '2015',
    chairs: ['Ian Robinson', 'Justin Wolf'],
    teams: [
      {
        name: 'Booking',
        executive: ['Michael Bass'],
        general: [
          'Max Goldberg',
          'Zak Kivitz',
          'Jacob Skaggs',
          'Jacob Frazer',
          'Yumiko Mannarelli',
          'Gina Garcia',
        ],
      },
      {
        name: 'Corporate',
        executive: ['Avi Small'],
        general: [
          'Tunde Kelani',
          'Danny Carlon',
          'Alex Rodosky',
          'Grant Rindner',
          'Zach Spohler',
          'Emma Felker',
          'Sydney Molano',
          'Jared Corak',
        ],
      },
      {
        name: 'Finance',
        executive: ['David Chi'],
        general: ['Nathan Frazer', 'Robert Hayes', 'Emma Montgomery'],
      },
      {
        name: 'Production',
        executive: ['Eliza Abramson', 'Allison Schloss'],
        general: [
          'Josh Schwartz-Dodek',
          'Alex Gold',
          'Kees DeVos',
          'Marylynne Anderson-Cooper',
          'Eli Panken',
          'Noah Piwonka',
          'Caroline Fearon',
          'Lauren Hutton Work',
        ],
      },
      {
        name: 'Promotions',
        executive: ['Steven Goldstein', 'Kalyn Kahler'],
        general: [
          'Joe Salwen',
          'Kaylah Sosa',
          'Ben Bass',
          'Justine Yucesan',
          "Elisa O'Neal",
          'Nikita Kulkarni',
          'Rachel Rogers',
        ],
      },
      {
        name: 'Special Events',
        executive: ['Arshia Sethi', 'Sam Schalop'],
        general: [
          'Chris Cortezi',
          'Gabrielle Ake',
          'Jenna Stoehr',
          'Luke Cianciotto',
          'Alexandra Robertson',
          'Rachael Ferm',
          'Ryan Kearney',
        ],
      },
      {
        name: 'Technology and Development',
        executive: ['Eric Brownrout'],
        general: [
          'Randall Harris',
          'David Ryan',
          'Philip Meyers',
          'Cary Murray',
        ],
      },
      {
        name: 'University Relations',
        executive: ['Matt Gallagher', 'J.P. Bowgen'],
        general: [
          'Keaton Sullivan',
          "Drew D'Alelio",
          'Jonathan Lopez',
          'Joe Fowler',
          'Frannie Trempe',
        ],
      },
      {
        name: 'General Board',
        executive: ['Ian Robinson', 'Justin Wolf'],
        general: [
          'Rovik Robert',
          'Andrew Hunter',
          'Ben Weinberg',
          'Ben Zimmermann',
          'Jimmy Song',
          'Daniel Kim',
          'Kody Keckler',
          'Lindsey Spohler',
          'Rachael Pennington',
          'Stephanie Minn',
          'Ali Lefkowitz',
          'Jacob Kogan',
          'Lisa Larbi',
          'Mikell Graves',
          'Andrew Jennings',
        ],
      },
    ],
  },
  {
    year: '2014',
    chairs: ['Patrick Leonard', 'Xander Shepherd'],
    teams: [
      {
        name: 'Booking',
        executive: ['Michael Bass'],
        general: [
          'Molly Goldberg',
          'Gina Garcia',
          'Jacob Skaggs',
          'Max Goldberg',
          'Zak Kivitz',
        ],
      },
      {
        name: 'Corporate',
        executive: ['Neil Mehta'],
        general: [
          'Avi Small',
          'Jared Corak',
          'Ton Luk',
          'Alex Rodosky',
          'Noah Star',
        ],
      },
      {
        name: 'Finance',
        executive: ['David Chi'],
        general: ['Lily Chang', 'Bob Hayes'],
      },
      {
        name: 'Production',
        executive: ['Justin Wolf', 'Nathan Frazer'],
        general: [
          'Allison Schloss',
          'MAC',
          'Alex Gold',
          'Eliza Abramson',
          'Eric Brownrout',
          'Spencer Reiss',
        ],
      },
      {
        name: 'Special Events',
        executive: ['Justin Wu', 'Katie Chilton'],
        general: [
          'Arshia Sethi',
          'Luke Cianciotto',
          'Rachel Schwab',
          'Ryan Kearney',
          'Sam Schalop',
          'Sarah Loughman',
          'Gaby Ake',
        ],
      },
      {
        name: 'Promotions',
        executive: ['Bri Hightower', 'Ian Robinson'],
        general: [
          'Mollie Block',
          'Shelly Tan',
          'David Ryan',
          'Julia Watson',
          'Kalyn Kahler',
          'Steven Goldstein',
          "Elisa O'Neal",
          'Ghikhan Blossfeld-Lau',
        ],
      },
      {
        name: 'University Relations',
        executive: ['Tori Zuzelo'],
        general: [
          'Jenna Powell-Malloy',
          'Frannie Trempe',
          'JP Bowgen',
          'Matt Gallagher',
          "Drew D'Alelio",
        ],
      },
      {
        name: 'General Board',
        executive: ['Patrick Leonard', 'Xander Shepherd'],
        general: [
          'Caroline Fearon',
          'Jonathan Lopez',
          'Kees DeVos',
          'Alex Robertson',
          'Ben Bass',
          'Chris Cortezi',
          'Daniel Carlon',
          'Eli Panken',
          'Emily Zanetis',
          'Jacob Frazer',
          'Joe Fowler',
          'Joe Salwen',
          'Joshua Schwartz-Dodek',
          'Justin Tepper',
          'Noah Piwonka',
          'Rachel Rogers',
          'Sam Shadrow',
          'Yumiko Mannarelli',
          'Zach Spohler',
        ],
      },
    ],
  },
  {
    year: '2013',
    error: 'We do not have accurate data for this year.',
  },
  {
    year: '2012',
    chairs: ['Darrin Bedol', 'Janna Kaplan'],
    teams: [
      {
        name: 'Booking',
        executive: ['Zach Robinson'],
        general: [
          'Aaron Garrido',
          'Jeremy Shpizner',
          'Max Brawer',
          'Roxana Obregon',
          'Xander Shepherd',
        ],
      },
      {
        name: 'Corporate',
        executive: ['Alex Cohen'],
        general: [
          'Avi Small',
          'Christine Hsaio',
          'Jade Chen',
          'Mariah Youngblood',
          'Neil Mehta',
        ],
      },
      {
        name: 'Finance',
        executive: ['Wil Heintz'],
        general: ['David Chi', 'Kelly Erickson'],
      },
      {
        name: 'Production',
        executive: ['Jon Glass', 'Logan Koepke'],
        general: [
          'Allison Zuzelo',
          'Demetrios Cokinos',
          'Emma Glass',
          'Maddy Armstrong',
          'Patrick Leonard',
        ],
      },
      {
        name: 'Special Events',
        executive: ['Bruna Giberti', 'Mitch Drew'],
        general: [
          'Abhit Bhandari',
          'Elsa Stahura',
          'Hayley Gleeson',
          'Jaclyn Skurie',
          'Katie Chilton',
          'Kelsey Pasmore',
          'Liv Jaeger',
          'Mallory Mattimore-Malan',
        ],
      },
      {
        name: 'Promotions',
        executive: ['Louise Hunter', 'Vivek Sudarsan'],
        general: [
          'Benjamin Estus',
          'Bri Hightower',
          'Elise Chagas',
          'Jessica Tackett',
          'Mollie Block',
          'Shelly Tan',
          'Steven Goldstein',
        ],
      },
      {
        name: 'University Relations',
        executive: ['Michael Campos'],
        general: ['Jesus Roman', 'Laura Schatz', 'Timothy Barrett'],
      },
      {
        name: 'General Board',
        executive: ['Darrin Bedol', 'Janna Kaplan'],
        general: [
          'Anthony Luk',
          'Arshia Sethi',
          'Elliot Lazar',
          'Gina Garcia',
          'Ian Robinson',
          'Jacob Skaggs',
          'Jean-Paul Bowgen',
          'Jenna Powell-Malloy',
          'Justin Wolf',
          'Justin Wu',
          'Michael Bass',
          'Mitchel Peterman',
          'Molly Goldberg',
          'Nathan Frazer',
          'Samantha Schalop',
          'Sarah Loughman',
          'Victoria Zuzelo',
          'Zoe Listernick',
        ],
      },
    ],
  },
  {
    year: '2011',
    chairs: ['Merrie Aaron'],
    teams: [
      {
        name: 'Booking',
        executive: ['Zach Robinson'],
        general: [
          'Mike Juliano',
          'Max Brawer',
          'Janna Kaplan',
          'Roxana Obregon',
          'Jeremy Shpizner',
          'Sabrina Lazarus',
        ],
      },
      {
        name: 'Corporate',
        executive: ['Alex Cohen'],
        general: [
          'Mariah Youngblood',
          'Severin Tsuji',
          'Neil Mehta',
          'Christina Assi',
          'Ryan Markmann',
        ],
      },
      {
        name: 'Finance',
        executive: ['Wil Heintz'],
        general: ['Japna Sethi', 'Kelley Erickson'],
      },
      {
        name: 'Production',
        executive: ['Darrin Bedol', 'Scott Winston'],
        general: [
          'Allison Zuzelo',
          'Logan Koepke',
          'Maddy Armstrong',
          'Jon Glass',
          'Shiraz Ahmed',
        ],
      },
      {
        name: 'Promotions',
        executive: ['Vivek Sudarsan', 'Austin Young'],
        general: [
          'Alex Freeman',
          'Danielle Chun',
          'Hayley Gleeson',
          'Jessica Tackett',
          'Louise Hunter',
          'Shelly Tan',
          'Stef Goliszewski',
        ],
      },
      {
        name: 'Special Events',
        executive: ['Becca Stewart', 'Bruna Giberti'],
        general: [
          'Elsa Stahura',
          'Abhit Bhandari',
          'Mitch Drew',
          'Katie Chilton',
          'Holly Baron',
          'Mallory Mattimore-Malan',
          'Joey Capuana',
        ],
      },
      {
        name: 'University Relations',
        executive: ['Josh Wasserman'],
        general: ['Michael Campos', 'Tim Barrett', 'Josh Bernick'],
      },
      {
        name: 'General Board',
        executive: ['Merrie Aaron'],
        general: [
          'Emma Glass',
          'Anne Hayford',
          'Jay Ribakove',
          'Mollie Block',
          'Liv Jaegar',
          'Lynn Carty',
          'Demetrios Cokinos',
          'Patrick Leonard',
          'Xander Shepard',
          'Laura Schatz',
          'Elise Chagas',
          'Alia Wilhelm',
          'Crystal Kim',
          'Aaron Garrido',
          'Jaclyn Skurie',
          'Brianna Hightower',
        ],
      },
    ],
  },
]);

function getLastName(member: RosterMember) {
  let name: string;
  if (typeof member === 'string') {
    name = member;
  } else {
    name = member.name;
  }

  const split = name.split(' ');
  return split[split.length - 1];
}

function sorted(roster: Roster) {
  return roster.map((year) => ({
    ...year,
    teams: year.teams?.map((team) => ({
      ...team,
      general: team.general.sort((a, b) =>
        getLastName(a).localeCompare(getLastName(b))
      ),
    })),
  }));
}
